# Generated by Django 4.2.11 on 2024-03-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=1)),
                ('vaccinated', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exotic_animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_of_origin', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=1)),
                ('vaccinated', models.BooleanField(default=False)),
                ('species', models.CharField(max_length=100)),
            ],
        ),
    ]
