# Generated by Django 4.2.11 on 2024-03-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_app', '0002_dog_exotic_animal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='age',
        ),
        migrations.AddField(
            model_name='owner',
            name='number_of_pets',
            field=models.IntegerField(default=0),
        ),
    ]
