# Generated by Django 4.2.11 on 2024-03-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_app', '0003_remove_owner_age_owner_number_of_pets'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='age',
            field=models.IntegerField(default=1),
        ),
    ]
